import type { Metadata } from "next";
import { Inter, Roboto_Mono } from "next/font/google";
import './globals.css'

const inter = Inter({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const robotoMono = Roboto_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${robotoMono.variable} ${inter.variable} antialiased light bg-gray-200 w-screen`}
      >
        {children}
      </body>
    </html>
  );
}
